### ISSUE TITLE
New mutators

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1078]
### Summary
maybe good mutators could be made of:
- ``>`` -> ``<``
- ``>`` -> ``===`` (etc)
- ``==`` -> ``===`` -> ``==``
- ``!=`` -> ``==`` -> ``!=``
- ``{ some object }`` -> ``{}``
- remove all ``cases`` from ``switch`` and leave only ``default``
-
- Based on https://stryker-mutator.io/mutators.html

**Comment by simondel** [comment]
Thanks for opening an issue for this!
We already support:
- ``>`` -> ``<``
- ``==`` -> ``===`` 
- ``===`` -> ``==``
- ``!=`` -> ``==`` 
- ``==`` -> ``!=``

Mutating case statements and switch statements sounds interesting! I don't really understand what you mean with
- ``>`` -> ``===`` (etc)
Could you be more specific on that one? Why is this a construction that you think should be changed?

**Comment by kmdrGroch** [comment]
@simondel ``etc`` v
- ``<`` -> ``===``
- ``>`` -> ``===``
- ``>=`` -> ``===``
- ``<=`` -> ``===``
It would test another cases.

**Comment by kmdrGroch** [comment]
Also i would like to notice that on your official page -> ``>`` -> ``<``; ``==`` -> ``===`` are not included; https://stryker-mutator.io/mutators.html

**Comment by simondel** [comment]
My bad! We actually don't have these mutators that I claimed we have.
- ``>`` -> ``<`` is already covered by ``>`` -> ``<=``
- ``==`` -> ``===``  will almost never cause an issue and the use of ``==`` is not recommended
- ``===`` -> ``==`` should never cause any issues except for linting

We could add the above mutators (same goes for the ``>`` -> ``===`` etc.) but since they are will almost never cause an issue that is not found using other mutators, I believe it's not the smartest move to add them. They will increase the time it takes to run stryker while not providing a lot of value.

What are your thoughts on this?
ps I still really like the object and switch mutators!

**Comment by kmdrGroch** [comment]
@simondel since ``>`` is changed to ``>=`` or ``<=`` you don't need ``===``. ``==`` -> ``===`` is really dumb (i was writing that at night so i was stupid then xD). You could also try emptying each object like ``Int8Array`` etc but i dunno if it won't cause some issue (or can be hard to implement)

**Comment by kmdrGroch** [comment]
@simondel i think this object replacer would look sth like
```ts
import { types } from 'babel-core';
import NodeMutator from './NodeMutator';
export default class ObjectExpressionMutator implements NodeMutator {
  name = 'ObjectExpressionMutator';

  mutate(node: types.Node, copy: <T extends types.Node>(obj: T, deep?: boolean) => T): void | types.Node[] {
    let nodes: types.Node[] = [];

     /* PseudoCode */
     if(typeof node === "object") {
         if(node.length > 0) {
            node = new (node.constructor.name)();
        }
        nodes.push(node);
     }
     return nodes;
  }
}
```

**Comment by jeffreyscholz** [comment]
I second the object mutators. I just had some tests pass that in one of my projects that should not have passed if the object was emptied.

**Comment by nicojs** [comment]
I'm closing this issue, since now have 2 new mutators! (Thanks @tommilligan, @kmdrGroch ). Please report a new issue per proposal from now on (so it is easier for issue tracking) 👍
