### ISSUE TITLE
Migrate to Lerna 3

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#1080]
Lerna 3 has been released. We should checkout what's different and migrate our project to it.

**Comment by Stukongeluk** [comment]
The result of upgrading to Lerna 3.4.0 and running the scripts defined in the `package.json` didn't result in any errors. (Only a deprecated warning for `commands` in the `lerna.json`).
This is expected, because Stryker isn't using any lerna commands which has had (documented) breaking changes. 

How much further do you want to research the new Lerna before it will be used in Stryker? @simondel

**Comment by simondel** [comment]
I'd like to test a release that also uses conventuonal-commits on both Windows and Linux to ensure a setup like ours still works (upgrading from Lerna 1 to 2 broke this for a while)

**Comment by nicojs** [comment]
> I'd like to test a release that also uses conventuonal-commits on both Windows and Linux to ensure a setup like ours still works (upgrading from Lerna 1 to 2 broke this for a while)

How do you want to do this? Just try it out and see what it does? (living on the edge!)

**Comment by simondel** [comment]
Just like how we tested it for V2, with a demo project

**Comment by simondel** [comment]
@nicojs sneaked this in somewhere.
