### ISSUE TITLE
Use npm scoped packages for stryker and its plugins

### ISSUE THREAD

**Issue by philippw** [stryker-mutator/stryker#1084]
### Summary

Since npm 2, npm supports [scoped packages](https://docs.npmjs.com/getting-started/scoped-packages#how-to-work-with-scoped-packages). In a nutshell, this allows for logically grouping parts of a project together.

Given that stryker comes with a useful set of plugins, it'd be nice to have such a group for them. E.g.:
So instead of ``stryker-jest-runner`` we'd get ``@stryker/jest-runner`` and so forth.

Other projects doing this are [angular](https://www.npmjs.com/search?q=%40angular) and [babel](https://www.npmjs.com/search?q=%40babel).

**Comment by simondel** [comment]
@nicojs Your plan was to do this with v1.0.0 right?

**Comment by nicojs** [comment]
Yeah, this is the midterm plan. We have our first scoped package here: https://www.npmjs.com/package/@stryker-mutator/util

Current timeline for 1.0 release will be probably something like Februari. Closing this issue for now, since we are using scoped packages.

Thanks for the great idea @philippw !
