### ISSUE TITLE
Documentation - (minor issue)

### ISSUE THREAD

**Issue by RichardHill** [stryker-mutator/stryker#113]
Hi, 
 There is an issue in the documentation - its an easy fix and simple issue - under usage there is the following line -:

"Using a config file node node_modules/stryker/src/Stryker.js -c stryker.conf.js"

It should read -:

"Using a config file node node_modules/stryker/dist/src/Stryker.js -c stryker.conf.js"

The addition of the dist directory that was omitted initially.

**Comment by simondel** [comment]
Hey Richard, the version of Stryker in the master branch no longer uses a dist folder. However, this feature has not yet been released. The best documentation for the current released version can be found over at [npm](https://www.npmjs.com/package/stryker) because that documentation only updates when we do a release.

The readme on the master branch also contains documentation for some arguments which are not supported in 0.3.2. so keep that in mind :)

If anything doesn't work for you, do let us know so we can fix it!
