### ISSUE TITLE
TypeError in HTML report

### ISSUE THREAD

**Issue by ollelauribostrom** [stryker-mutator/stryker#1426]
### Summary
The HTML report page generates a TypeError saying:
```
stryker.js:1089 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at stryker.js:1089
    at Object.3.highlight.js/lib/highlight.js (stryker.js:1126)
    at o (stryker.js:1)
    at r (stryker.js:1)
    at stryker.js:1
```
This shows up in the console when viewing the "report landing page". Im guessing that happens beacuse [this line](https://github.com/stryker-mutator/stryker/blob/1c71ea4ae1d4e9ae94850b7ea010efe3a79bf8ff/packages/html-reporter/srcResources/stryker.js#L82) tries to add an event listener to a button that only exists on the "report for a file" page. If you think it's worth fixing, I'm up for submitting a PR 🙂 

### Your Environment
@stryker-mutator/html-reporter: ^1.0.2
OSX 10.11.1
Chrome Version 72.0.3626.119

**Comment by nicojs** [comment]
Awesome catch! 😎. Also, I feel a bit embarrassed, since it isn't the prettiest piece of code 😉 

>  If you think it's worth fixing, I'm up for submitting a PR 🙂

We're actually creating a new implementation of the html reporter over at [mutation-testing-elements](https://github.com/stryker-mutator/mutation-testing-elements) based on web components. So it's up to you. Your fix would be faster, but if you wait a month or so, it will be replaced entirely.

**Comment by ollelauribostrom** [comment]
Nice, didn't know of that 👍Then I don't see any point of fixing this now since it does not seem to affect any functionality 🙂

**Comment by simondel** [comment]
This should be fixed now 🎉 More info: https://stryker-mutator.io/blog/2019-04-03/one-mutation-testing-html-report
