### ISSUE TITLE
Support `--files` in mocha.opts

### ISSUE THREAD

**Issue by glezalex** [stryker-mutator/stryker#1428]
I'm trying to run Stryker on a Vue project with webpack and after fixing some other issues -mainly npm package errors- I'm stuck with this error:

`Error: [vue-test-utils]: window is undefined, vue-test-utils needs to be run in a browser environment. 
You can run the tests in node using jsdom`

I've created a quick-and-dirty example at [https://github.com/glezalex/vue-tdd](https://github.com/glezalex/vue-tdd) to show an example of this error, in case somebody could help me understand where this issue comes from :).

**Comment by nicojs** [comment]
@glezalex thanks for opening this issue.

@simondel or @Archcry could one of you take a look? You guys are vue experts, right?

**Comment by simondel** [comment]
Glad to see some Vue people around here! Thanks for the repro repo :) I'll check it out tomorrow ♥️

**Comment by glezalex** [comment]
@simondel thanks a lot! I'm playing around with your fork and it works like a charm. Also your commits are of great help to me to learn some tricks.

**Comment by simondel** [comment]
No problem! I've also submitted my changes as a PR to your repo :) 

I've reopened this issue because the error is still there if I use the mocha test runner programmatically from Stryker.

**Comment by simondel** [comment]
Alright, so the problem is this:
You load `jsdom-global` in `test/setup.js`. This file is loaded by your `test/mocha.opts` file:
```
--file test/setup.js
```
The file is in the default location so it's always loaded, however, Stryker doesn't do anything with your specific mocha.opts file because:
> The only supported mocha options are used: --ui, --require, --async-only, --timeout, --grep (or their short form counterparts). Others are ignored by the @stryker-mutator/mocha-runner.

(as per the [@stryker-mutator/mocha-runner readme](https://www.npmjs.com/package/@stryker-mutator/mocha-runner#mochaoptionsopts--string--false))

Stryker should log that it ignores the option because of this line of code:
https://github.com/stryker-mutator/stryker/blob/master/packages/mocha-runner/src/MochaOptionsLoader.ts#L85
but for some reason it doesn't do that..

In my local file system I've changed the logging to warning and then it does show the logging:
![image](https://user-images.githubusercontent.com/4221997/53663996-86a88580-3c67-11e9-99f7-7f81a5ab017c.png)

**To sum it up**
We have a few issues:
1. We don't load files that are specified in the mocha.opts file. We could just load these to your mocha files before we load the regular mocha files and we should be fine.
2. The logging that warns you of ignored properties doesn't show at all
3. The logging is debug logging. Since it results in us running in a different setup then a regular testrun I would expect it to be logLevel `warn`.
4. The logging shows the key of the option, not the entire option. I think the message `Ignoring option "--file test/setup.js" as it is not supported.` would be more clear than the one you can see above in the screenshot.

@nicojs What are your thoughts on my remarks?

@glezalex Thanks for making us aware of this! Feel free to take another look at my fork, I've updated it with the latest config 👍

**Comment by simondel** [comment]
Also, I noticed #1433 because of this issue 👍

**Comment by nicojs** [comment]
1. What's the difference between `--file` and `--require`. I honestly dislike the mocha.opts file a lot. Why don't the mocha guys provide an API to load options. Its very hard to keep up with is.
2. Why not?
3. I disagree. For example `--exit` should just be ignored, as it doesn't make sense for Stryker. Logging these things on warn forces people to maintain 2 sets of configuration
4. Agreed

**Comment by glezalex** [comment]
Thanks again @simondel, I've already incorporated your fixes to my repo and it really exceeds what I expected -and needed 😄-. I'm working with another colleague on a very basic example for an event in which we would like to show stryker in action and this is of great help.

**Comment by simondel** [comment]
`--file <file/directory/glob>`
Explicitly include a test file to be loaded before other test files files. Multiple uses of --file are allowed, and will be loaded in order given.

Useful if you want to declare, for example, hooks to be run before every test across all other test files.

Files specified this way are not affected by --sort or --recursive.

Files specified in this way should contain one or more suites, tests or hooks. If this is not the case, consider --require instead.



`--require <module>, -r <module>`
Require a module before loading the user interface or test files. This is useful for:

Test harnesses
Assertion libraries that augment built-ins or global scope (such as should.js)
Instant ECMAScript modules via esm
Compilers such as Babel via @babel/register or TypeScript via ts-node (using --require ts-node/register)
Modules required in this manner are expected to do work synchronously; Mocha won't wait for async tasks in a required module to finish.

Note you cannot use --require to set a global beforeEach() hook, for example — use --file instead, which allows you to specify an explicit order in which test files are loaded.

**Comment by simondel** [comment]
I'm able to run Stryker on the vue-tdd repo as well if I change
`--file test/setup.js` into `--require ./test/setup.js` (the relative path is important, since it's a local file)

**Comment by nicojs** [comment]
> I'm working with another colleague on a very basic example for an event in which we would like to show stryker in action and this is of great help.

Just be sure to send pics or even tweet about it, we'll retweet ([@stryker-mutator](https://twitter.com/stryker_mutator))

@simondel 

Thanks for the documentation. I guess we should parse & support `--file` as well. It is too bad that we need to keep this functionality in sync. We could also log all unknown options on `warn` level. So we would keep logging `--exit` on debug, but `--some-fancy-feature` would be logged on `warn`

@glezalex would you mind if we change the name of this issue to reflect this new functionality? "Support `--files` in mocha.opts" (or something).

**Comment by glezalex** [comment]
We'll for sure, thanks @nicojs.

Yes sure, if finally better reflects the actual issue so the original name I gave it could be misleading.
