### ISSUE TITLE
Target es2015 (or 2016/2017?)

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#1516]
For the 2.0 release we should try to go as high as we can using typescript's target property. We should be able to support async natively.

**Comment by kmdrGroch** [comment]
@nicojs if I get what you mean by `async` we should use at least es2017 (look: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)

But I guess since we are removing IE from supported browsers (hello ES6+), we could use es2018 or even esnext build target (since modern browsers such as Firefox and Chrome keep their engines up to date with current ECMAScript standards (or at least do their best

**Comment by nicojs** [comment]
> But I guess since we are removing IE from supported browsers (hello ES6+), we could use es2018 or even esnext build target (since modern browsers such as Firefox and Chrome keep their engines up to date with current ECMAScript standards (or at least do their best

Not sure why we care about browsers. Stryker only runs on node. We can use https://node.green/ as a resource, but we also feel confident relying on our travis build for this.

**Comment by kmdrGroch** [comment]
if you want to support Node8+ I guess es2018 should work too (not sure in 100%, but most likely), if not, es2017 is going to work

**Comment by simondel** [comment]
We're doing this now so I'll close this issue for now.
