### ISSUE TITLE
Stop running tests when block test failed (optimization)

### ISSUE THREAD

**Issue by jRichardeau** [stryker-mutator/stryker#1562]
### Summary

This is not a bug but a question of how to optimize stryker run.

My team and I want to use stryker to validate our tests efficiency but the duration of the execution is a big issue for us.

So I would like to know if we could optimize it ?

For instance could test runners stop testing code blocks if the "block mutator" fails ?
This could avoid executing some tests that will always fail (right ?).
Maybe there is a config for it ?

Thanks

**Comment by nicojs** [comment]
>  This could avoid executing some tests that will always fail (right ?).

I'm not sure I understand this correctly. If you're just interested in the "block mutator", you could filter for only those mutations by excluding the rest. See this: https://github.com/stryker-mutator/stryker/tree/master/packages/core#mutator-object--string

Next, you could make Stryker fail your build by setting the [thresholds.break](https://github.com/stryker-mutator/stryker/tree/master/packages/core#thresholds-object) to 100

**Comment by simondel** [comment]
This is quite an interesting idea! The execution, however, is a bit ticket because of a couple of reasons:
1. Mutations are often tested in parallel. If you want to stop testing 'child' mutations after the parent has survived, you need to store the parent-child relationship somehow and ensure that processes get a set of mutations instead of just single mutations.
2. Smaller mutations may make a different change than a big mutation. A block mutation, for example, may change the return type of a method causing an exception (or TypeScript compiler error). A change such as `a + b` => `a - b` may not cause any issue but may subtly change the way your program work.

A block mutation may not be the best use case to optimize this. Boolean mutations could be more reliable.

Take the following code:
```js
if(a && (b || c)) {
   ...
}
```
We could mutate this into:
```js
if(a && (b && c)) {
if(a || (b || c)) {
if(a && (true)) {
if(a && (false)) {
if(true) {
if(false) {
```
If the mutation `if(false) {` survives, we can safely assume that `if(a && (false)) {` also survives. Checking for this in Stryker will be quite tricky though, since the code could also be `if(a && d || (false)) {`
If the mutation `if(false) {` AND `if(true) {` both survive, we can safely assume that the other mutations will also survive. This is relatively easy to check since we only have to check the 'root' mutations and won't have to take into account other code that is present in the if-statement

**Comment by jRichardeau** [comment]
@nicojs I should say this could prevent running unnecessarily tests ;)

Thank you for your answer @simondel, so it could be a good idea but complicated to do ?

As it I'm afraid it's not suitable for us because we can't wait 10+ minutes per file in development to validate our tests efficiency :/, even if I understand why it takes this time.

We have to think about how to integrate it in our dev process.

**Comment by nicojs** [comment]
> As it I'm afraid it's not suitable for us because we can't wait 10+ minutes per file in development to validate our tests efficiency :/, even if I understand why it takes this time.

What is your current stryker.conf.js. We might be able to help there.

We're also thinking of implementing [mutation-switching](https://stryker-mutator.io/blog/2018-10-6/mutation-switching). There are also other ideas like incremental mutation test runs.

These all take time, since we're only able to work on this project part-time.

**Comment by jRichardeau** [comment]
`mutation-switching` is not only for scala ?

Here is my stryker.conf.js : 
```js
module.exports = function(config) {
   config.set({
      mutate: ["source/**/*.js", "!source/**/*@(.test|.spec|Spec).js", "!source/scripts/**/*.*"],
      files: [
         '*.js', 
         '__mocks__/*.js',
         'testUtils/*.js',
         'source/**/*.js?(on)',
         "!source/scripts/**/*.*"
      ],
      mutator: "javascript",
      packageManager: "yarn",
      reporters: ["html", "progress"],
      htmlReporter: {
         baseDir: 'stryker-reports/mutation/html'
      },
      testRunner: "jest",
      coverageAnalysis: "off",
      jest: {
         projectType: "custom",
         config: require('./jestrc.json'),
         enableFindRelatedTests: true
      },
      symlinkNodeModules: false
   });
};
```

**Comment by nicojs** [comment]
> mutation-switching is not only for scala ?

The concept of adding all mutations at once to the source code isn't specific for Scala. We think it could also have a big impact for JS. Namely not having to reload your entire project between each run just to update one mutation. We could simply load all files once and keep running the tests while switching which mutation is active.

I see you're using Jest. It's not the fastest test runner. Since it does a lot of work under the hood, we're not able to get coverage analysis working (which is why it is 'off'). We will revisit the implementation of the jest runner once we're implementing mutation switching. It will be easier to add support then I think. 

What you could do if you really wanted is dynamically decide which test files to load using your local git changes. For an example: see the stryker-diff-runner. https://github.com/tverhoken/stryker-diff-runner

That way, you might be able to run Stryker in CI mode as well as nightly (all files)

**Comment by simondel** [comment]
This is not something we'll do right now as I believe that mutation switching is more benificial

**Comment by simondel** [comment]
This is not something we'll do right now as I believe that mutation switching is more beneficial
