### ISSUE TITLE
[REQ] Output Coverage report as LCOV

### ISSUE THREAD

**Issue by InfoSec812** [stryker-mutator/stryker#1568]
### Summary

It would be nice to have a coverage report file which can be ingested by tools like SonarQube or SonarCloud

### Stryker config

Ideally, a new `reporter` option of `lcov` would be available.

**Comment by nicojs** [comment]
Wow, that would be cool! 😍 

We're preparing to change the inner workings of stryker in order to use [mutation switching](https://stryker-mutator.io/blog/2018-10-6/mutation-switching). It would mean that we'll instrument the code with all mutants at once. It also means that we'll be able to remove the dependency on istanbul (code coverage instrumenter), since we'll be able to collect coverage directly from mutants. 

I don't want to add that feature now since we'll be rewriting this core part in the next year. If we were to generate `lcov` output after the rewrite, it wouldn't be accurate, since we won't be counting lines coverage, branch coverage or function coverage. Instead, we would be counting _mutant coverage_. 

I'm not an expert on the `lcov` specification. Does it allow for new counters like "mutant coverage"? If so, we could add this feature in the future. If not, I think we should close this issue. Code coverage is not the main focus of Stryker, at best a nice to have by-product.

**Comment by InfoSec812** [comment]
Can we re-open this now that 4.x is out?
