### ISSUE TITLE
slowly prepare to drop node 8 support

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1611]
Since Node 8 is ending its life in 2019-12-31, we should slowly start preparing at least 'todo' list (half a year seems to be a short period of time, but we might run out of time).

- I guess all 'promisify' stuff will disappear since node 10 supports promised version of most of functions (in node 10 it's experimental - in node 12 it's stable)

It might be a chance to release Stryker 3.0,
maybe do stuff like: (#1610, #1457), #1589, #1514, #1508, #1472, #1473 try to clean up issues a bit (which are solved, which aren't or won't)

**Comment by nicojs** [comment]
This is a bit early IMHO 😅 

As for your issues.

* #1589, #1472, #1473, #1457, #1610 can be done whenever we want. No need to wait for a major release, since they shouldn't require a breaking change.
* #1514 requires a major change in how mutation is done. I've discussed this face to face with @simondel  and the easiest thing will be to build it next to the current mutation implementation and let people opt-in with an `--expermimentalMutationSwitching` command line flag (or something like it). That way we can actually release it before we remove the old implementation while keeping it all backward compatible. I'll update #1514 as well.

@kmdrGroch would you agree with this? In that case, we can just keep this issue open and focus on the removal of all legacy and deprecated code.

**Comment by kmdrGroch** [comment]
@nicojs I was thinking also in dropping node 8 support which is a bit breaking (goodbye node8 users). But yea, no need to hurry, just pointing out, in my opinion, things should be done
