### ISSUE TITLE
React `propTypes` mutation.

### ISSUE THREAD

**Issue by rodoabad** [stryker-mutator/stryker#1653]
**Question**

When we're writing  React component, we typically write `propTypes` validations so we know that the props we're passing to a component is of the correct type.

Stryker is mutating these though even though they are for development purposes.
<img width="503" alt="Screen Shot 2019-07-21 at 6 41 29 PM" src="https://user-images.githubusercontent.com/1240667/61598744-8c3b4380-abe7-11e9-8a8c-f6f780d611e4.png">

For those who have actually prevented Stryker from mutating these, what did you do?

**Comment by kmdrGroch** [comment]
For now i guess this is a bug. I don't see workaround. We might need to add some option to exclude given line or sth like this, the way it is done ex. in tslint or eslint

**Comment by simondel** [comment]
Hi! Right now this is not possible to exclude. We have a general feature request for this: #1472 
As there is a general issue open, I'm closing this issue for now.

**Comment by itsmeraji** [comment]
Hi, our team is interested in using Stryker to get the mutation test results, but almost all the files get this propTypes mutated and it brings the mutation test score down. We would like to know is there a possibility to exclude propTypes from getting mutated in Stryker. Is there any progress made on this?

**Comment by kmdrGroch** [comment]
@itsmeraji I'll start working on #1472 very soon. It should be done until the end of this month I hope

**Comment by itsmeraji** [comment]
@kmdrGroch, Thank you for the reply. But will it be possible to add some configuration in Stryker.conf and disable proptypes mutation in all files automatically, based on the configuration ? If we have to add ignore comments, we ve to add ignore comment for proptypes in all the files..

**Comment by kmdrGroch** [comment]
@itsmeraji, for now, we are only planning to add the comments-based exclusion. In the future, we could write some plugin for it, but no hopes right now.

**Comment by itsmeraji** [comment]
@kmdrGroch, is there any update on this feature? I see PR #1810 created for this.

**Comment by kmdrGroch** [comment]
It is still being worked on. Unfortunately this issue is quite complex so it takes time :<

**Comment by itsmeraji** [comment]
@kmdrGroch , I understand. I have been trying other options to ignore prototypes from mutation. I wrote a custom transpiler to remove a node if it has propTypes in assignment expression. When applying this as plugin in Babel and Jest transform, propTypes gets removed when I run a test. But the plugins / transpilers options in Stryker configuration doesn't allow a custom transpiler plugin like this. Even the plugins option within the mutator object allows only the plugins provided within babel-parser. Do you have any suggestions for me here ? To make the custom transpiler get applied before Stryker generates mutants ? We are blocked due to this.
