### ISSUE TITLE
Support mocha v6.2

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1693]
It seems we've got some strange errors (caused by us I suppose)

https://travis-ci.org/stryker-mutator/stryker/jobs/578878785#L2266  -  error in real life

https://github.com/stryker-mutator/stryker/blob/master/packages/mocha-runner/src/MochaTestRunner.ts#L54  -  emitting place

**Comment by nicojs** [comment]
I think this is mostly because of this change in mocha: https://github.com/mochajs/mocha/commit/15b96afccaf508312445770e3af1c145d90b28c6#diff-39b692a81eb0c9f3614247af744ab4a8

We're relying on a private api to read files and load options. Unfortunately, mocha doesn't have a public API for this. See https://github.com/mochajs/mocha/issues/3882 for more info.

If they don't provide a public api, the only thing we can do is rely on their private api, or copy-paste the relevant code and keep it in sync. Both far from ideal.
