### ISSUE TITLE
ESlint migration

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1719]
Should I start working on migration to ESlint soon?
https://github.com/palantir/tslint/issues/4534
since we are close to the `November 1st, 2019` mark, I think we could be thinking about implementing it sooner or later

**Comment by kmdrGroch** [comment]
I'll slowly start migrating our config since next week. It would be nice if you assign me so I don't forget about it ;D Also I have already known about that tool, although it still has some issues I guess I can handle it more or less :)

**Comment by nicojs** [comment]
Probably this will be a good time to introduce prettier as well (#1271) using the prettier plugin for eslint. Instead of migrating our config, we could also base our config on Airbnb's one (https://www.npmjs.com/package/eslint-config-airbnb-base), since it would save us a lot of time, as well as being aligned with somewhat of an industry standard. What do you think about this?

I'll publish a small setup (something like "typescript-eslint-rbnb-prettier-starter") to github soon since I'm working on that for my day job at the moment. Probably later today.

**Comment by kmdrGroch** [comment]
well, isn't it better to keep our config like it is right now (I would like it even 'stronger' since some whitespaces are quite annoying in some places, but whatever), I will do it in a few days since I have just finished exams on the university. And sure I can work with prettier. But do you want me to add both eslint and prettier in one PR or should I make 2 separate PRs?

**Comment by nicojs** [comment]
This is an example: https://github.com/nicojs/typescript-eslint-prettier-starter

> well, isn't it better to keep our config like it is right now 

That's fine 2. It will save another dev-dependency we need to maintain, so good decision.

> prettier in one PR or should I make 2 separate PRs

You can make it 1 PR, I don't mind. Let's keep a `printWidth` for prettier of 100 or something (not too small).

> I will do it in a few days since I have just finished exams on the university

Much success my friend! Hope you do well! 🤞
