### ISSUE TITLE
possible overflow fix

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1761]
For now, we are using an array to store mutants and files etc.
We could try a different approach ->

Transpile file -> create mutants for this file -> test mutants

instead of

Transpile all files -> create mutants for all files -> test all mutants

This could help with overflows of data (big arrays = big problems)

We would "earn O(n) space complexity for files", and speed would decrease for the "create n arrays instead of 1 for mutants"

**Comment by simondel** [comment]
I have thought about this as well. It has some downsides and some upsides.

### The good
* The code (and process) of Stryker becomes less complex
* It's a faily cheap (developer time wise) fix for issues that have been going on for a while
* We can run an extra test runner on the thread of the transpiler. This _may_ increase performance (if we aren't on 100% system use with the current setup)

### The bad
* The overall performance of Stryker will most likely decrease because we can't transpile ahead of the testrunner, while it is running.


@nicojs what are your thoughts on this?

**Comment by nicojs** [comment]
First of all, I'm not sure the large array is the problem here. An array in JavaScript isn't an allocated block on the heap like they are in C++, C#, Java, etc.

For example: this command executes without a problem `node -e "const arr = []; for(let i=0; i< 9999999;i++){ arr.push(i); }"`

So I'm not convinced that the large array is the problem in #1779. As you can see, it managed to generate the actual `26902` mutants. So the array is there.

The mutation test execution process (https://github.com/stryker-mutator/stryker/blob/2bb7dd8b6f605eac29ba4af0463aa0cc4f395af2/packages/core/src/process/MutationTestExecutor.ts) already uses reactive streams for the most part. In other words: it transpiles a maximum of 100 mutants and then waits for a free slot (i.e. a mutant to be tested) before transpiling another one (even when you didn't configure a transpiler this still holds true because we're using a 'passthrough transpiler' under the hood).

So we could make the entire process reactive with our (self-invented/poor man's) back pressure technique we're using for that inside the `MutantTranspileScheduler`. We would basically move this code up several levels for it to also spawn the mutant generator process:

https://github.com/stryker-mutator/stryker/blob/2bb7dd8b6f605eac29ba4af0463aa0cc4f395af2/packages/core/src/transpiler/MutantTranspileScheduler.ts#L21-L39

Some remarks:

* This would mean a breaking changes for our reporter API: https://github.com/stryker-mutator/stryker/blob/2bb7dd8b6f605eac29ba4af0463aa0cc4f395af2/packages/api/src/report/Reporter.ts
* This would also mean that we cannot collact the results at the end in an array anymore, so reporters should do some gymnastics to write a report to disk
* It would mean an entire rewrite of our code.

I'm not saying that we shouldn't do it, I just want to make 100% sure there is no other alternative.

I think the problem with #1779 can be found elsewhere. I'll add a comment there.
