### ISSUE TITLE
Stryker integration with GitHub CI/CD?

### ISSUE THREAD

**Issue by cpilson** [stryker-mutator/stryker#1785]
Greetings. I didn’t see GH as a supported CI. I’d anticipate people will start using GitHub’s actions (I think this is what they’re called) to do light to moderate CI work. It may be beneficial to add support for this.

**Comment by nicojs** [comment]
Hi @cpilson. I'm not sure what the issue would be to run Stryker in github actions (via a workflow) with the a [run step](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun). We're actually busy with that ourselves to enable running stryker on stryker in nightly builds.

Or are you referring to having it automatically send the results to the Stryker dashboard? I've created #1792 for this and planning to pick it up shortly.

Closing this issue for now because it isn't really an issue. Please add a comment if you still have questions.
