### ISSUE TITLE
Make use of the new features of TypeScript 2.1

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#190]
TypeScript 2.1 has officially been out for little over a week. Time to think about upgrading!

You can find the release notes here:
https://blogs.msdn.microsoft.com/typescript/2016/12/07/announcing-typescript-2-1/ and here https://blogs.msdn.microsoft.com/typescript/2016/11/08/typescript-2-1-rc-better-inference-async-functions-and-more/

The most interesting part for me is async-await support. I think it could replace many promises in our code making it more readable. What do you think about TypeScript 2.1 @nicojs?

**Comment by nicojs** [comment]
Yes please. Async and await will clean up a lot of our code. We should also enable these compiler options (available since 2.0)

```json
"noUnusedLocals": true,
"noImplicitReturns": true,
```

Should we split this in multiple PRs?

1. Upgrade the compiler to 2.1. Nothing else, just upgrade (should be done for other repo's as well).
2. Enable and fix noUnusedLocals + noImplicitReturns (already done for most of our repo's).
3. Replace all `promise.then` with `async`/`await` (should be done for other repo's as well)..

**Comment by simondel** [comment]
I think it would be a good idea to split it :) It may be smart to introducre `async`/`await` last in the Stryker repo. This repo will be the most work to upgrade so by the time we get to upgrading Stryker we already have some experience.

**Comment by Archcry** [comment]
I refactored some code in order to support the noImplicitReturns and noImplicitLocals flags for typescript. I also set these flags to true in the tsconfig.json for this repo. Will open a pull request sometime soon.

**Comment by Archcry** [comment]
I think this  issue can be closed?

**Comment by nicojs** [comment]
Yep. Thanks
