### ISSUE TITLE
Add support for tape

### ISSUE THREAD

**Issue by jeznag** [stryker-mutator/stryker#211]
WIP https://github.com/jeznag/stryker-tape-runner

**Comment by simondel** [comment]
> @jeznag in #176:
> I've put a POC together https://github.com/jeznag/stryker-tape-runner/blob/master/src/TapeTestRunner.ts but am a bit confused by the TestFramework part. What do I have to do there? Can I leave that out?

The `stryker-mocha-runner` that you took as an example contains two parts: the TestRunner and the TestFramework. The TestRunner is responsible for making sure the tests are actually executed while the TestFramework can help by filtering the tests that are executed. 

This filtering is done based on code coverage. Stryker is capable of instrumenting code using Istanbul, but in order to do that for every single `it` it needs to execute a bit of code before and after each test to know how the code coverage has changed. This is why a TestFramework has the methods `beforeEach` and `afterEach` which should return bits of code that should be executed before and after each test. This code is then combined and saved as a file so it will be used during testing. You can see that code [here](https://github.com/stryker-mutator/stryker/blob/c17ecc9a550559155cadb8d656402181ecbfa4bd/src/coverage/CoverageInstrumenter.ts#L50).

Now, what can you leave out? Everything. We can run without a TestFramework implementation because all it does is increase performance. So I would suggest you ignore the TestFramework for now and just focus on the TestRunner :)

@nicojs Do you have anything to add?

**Comment by jeznag** [comment]
@simondel @nicojs Can you advise what I need to do for the TestFramework file?

**Comment by simondel** [comment]
Whoops. Wrong button. Thanks for reopening!

**Comment by jeznag** [comment]
Ok thanks for clarifying. I added in some placeholder methods for the test framework. Looks like it will be a bit of effort to get it working with istanbul. I might leave off support for coverage for now.

**Comment by jeznag** [comment]
Am testing it and am a bit stuck. Am running it on https://github.com/jeznag/empath-sentiment-analysis using babel-node to handle ES6

I'm getting this error:
```
[2016-12-31 20:10:57.890] [ERROR] IsolatedTestRunnerAdapter - (node:20160) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'coverage' of undefined

[2016-12-31 20:10:57.891] [ERROR] IsolatedTestRunnerAdapter - (node:20160) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jeznag** [comment]
@simondel have got it working now (I was just using the wrong status code to indicate completion).

Some questions:
1. Have you seen these warnings before? I thought it might be the tape object stream but I tried commenting that out and I still get the warning.
![image](https://cloud.githubusercontent.com/assets/1034890/22860439/3ee013c4-f152-11e6-92bf-bc8ca207f1f6.png)

2. Noob question: with this config, no files get mutated. How should I do it if I only want a few files to be mutated?
```
files: [
      'test/tape/**/*.js',
      { pattern: 'src/**/*.js', included: false },
      { pattern: 'src/analyseSentiment.js', included: false, mutated: true },
      { pattern: 'src/sentimentWordList.js', included: false, mutated: false },
    ],
```

**Comment by lirantal** [comment]
Can we include Ava.js support for this capability? I'd love to try it out in my code base.

**Comment by simondel** [comment]
@jeznag 
1. We've had this before (https://github.com/stryker-mutator/stryker/issues/115) but we fixed it by adding `included: false`, which you're using. Any ideas @nicojs ?

2. The `InputFileResolver` can detect if you have duplicate files in your config and it will always use the first occurance it finds. In this case it will find `src/analyseSentiment.js` as a part of `{ pattern: 'src/**/*.js', included: false }` and turn it into `{ pattern: 'src/analyseSentiment.js', included: false, mutated: false}`. After that it will find your second definition of the file, with `mutated: true` but it will be ignored. Could you try moving `{ pattern: 'src/**/*.js', included: false }` to the bottom of the file list?

@lirantal I'm not familiar with Ava.js. Is it a test runner and test framework in one?

**Comment by lirantal** [comment]
Ava.js is a test runner, they took a lot from tape so they are very similar from syntax perspective and it has really grown: https://github.com/avajs/ava

**Comment by simondel** [comment]
@lirantal Sounds good! Could you open a new issue so we can discus it there?

**Comment by lirantal** [comment]
Definitely, thanks Simon.

**Comment by jeznag** [comment]
@simondel Have got the tape runner running nicely now + tests apart from the MaxEventListeners issue: https://github.com/jeznag/stryker-tape-runner
Want to review the code and consider bringing it into the stryker-mutator org?

![image](https://cloud.githubusercontent.com/assets/1034890/24076805/56e7bca4-0c8e-11e7-98b2-0cee52a185ce.png)

**Comment by simondel** [comment]
Sounds great! I created a [repository for you](https://github.com/stryker-mutator/stryker-tape-runner) and gave you permissions. If you want to retain your history you could transfer ownership to move the repo. If you happen to lose access in the process, we'll make you admin again 👍

**Comment by jeznag** [comment]
Sweet merged in your changes and pushed up the code to the new repo. Will close this now and monitor any issues that come through :)
