### ISSUE TITLE
HTML Report in one single file 

### ISSUE THREAD

**Issue by HonzaMac** [stryker-mutator/stryker#2188]
**Is your feature request related to a problem? Please describe.**

We are using Jenkins for builds and we are attaching mutation html report as artefact.

![image](https://user-images.githubusercontent.com/3055648/81700718-58c4f080-9469-11ea-8853-cb6917669bce.png)

Problem is, when I click on report I see only that custom elements are not supported. 
Root cause are security policies for downloading/linking files from html file for JS files.

<img width="1866" alt="Screenshot 2020-05-12 at 15 59 58" src="https://user-images.githubusercontent.com/3055648/81701066-ca9d3a00-9469-11ea-9936-d2b7243259a5.png">

User receive errors from loading JS files.

**Describe the solution you'd like**

It would be best, if all 3 required files would be inlined in one html report. 
We would not need any alowance and sending over this report would be far easier then using compressed files.

**Comment by nicojs** [comment]
Thanks @HonzaMac for opening this feature request.

I've tried to merge it all into one file once before. However this poses a problem if your JavaScript source code has a string `'</script>'`, as it will close the html script tag. I didn't want to spent a ton of time investigating it. 

Do you know a way around the issue? Otherwise I guess we could enable it with an optional config setting.

**Comment by HonzaMac** [comment]
@nicojs I think we should go with escaping of that values. 
Do you have in some branch that "merge" into files? I can follow up and fix escaping.

**Comment by HonzaMac** [comment]
Thank you!

**Comment by nicojs** [comment]
Sure thing! We will release a new version later this week.
