### ISSUE TITLE
Get control over dependencies

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#2330]
Right now, the only support for dependencies we get is Dependabot. Which unfortunatelly has its limitations. So far, I have noticed it doesn't check packages deeply, so while we try maintaining packages in root directory, other (like 10) packages have VERY outdated dependencies (just check some logs while running E2E [we have over 3000 minor issues { says NPM }] throughout the application).
Things that should be done (the faster the better [I know we can do it anytime, but this anytime was several years ago now ;) ]):
1. Configure dependabot so it checks package.json inside packages, e2e etc.
2. FInally update types! Guys we are using 5.0.5 for sinon (THERE IS 9x!)
3. Update the rest of packages *if possible
4. Change ^ to ~ for all packages [or even ""] (unless it has to be "" (linting) or "^" (node, peerDeps)) {or use lockfiles?} - it will require more merging, yes, but on the other hand we will have better control over packages and smaller chance of "breaking change" during minor release (like NYC once had and probably several other packages) and better support over other issues (look #2278)
5. Decide if we want Node@CurrentX or Node@MinimumSupportedX, since its quite inconsistent - 14x v 10x

**Comment by nicojs** [comment]
Thanks for opening this issue! 

> Configure dependabot so it checks package.json inside packages, e2e, etc.

I don't think this is as simple as that. Inside `e2e/test`, there are projects that need their own maintenance lifecycle. For example, angular projects can't simply update dependencies to `rxjs` or `typescript`, they need to wait for the next major version. So what we need to do is to schedule a recurring issue for that every 6 months. 

However, I think the `e2e` project itself should be able to version automagically with dependabot. Most projects use the dependencies of the `e2e` project itself to run, I think only 4 projects don't, so that would already provide a big improvement.

> FInally update types! Guys we are using 5.0.5 for sinon (THERE IS 9x!)

Types should be updated with dependabot like everything else. `@types/sinon` is an exception here. It's mostly https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36019 that is holding is back. I'm willing to give it another shot after our v4 release. I've created #2337 for this purpose.

> Change ^ to ~ for all packages

I agree we should use `~` for everything _except_ our own dependencies (`@stryker-mutator/api`, `@stryker-mutator/util`, etc). Can we add a linting rule for this? 

> or use lockfiles?

@simondel and I went back and forth on the use of lock files, and we eventually vote against it. Yes, it sucks when the pipeline fails because of an update of a dev dependency, however, we _do like it_ if the pipeline fails because of an update of a dependency since it might signal bad use of semver by that dependency which breaks Stryker, or Stryker relying on a private API which changed in a patch release. More people in the nodejs community think that lock-files are a bad practice for libraries and CLI tools. See https://www.twilio.com/blog/lockfiles-nodejs 

> Decide if we want Node@CurrentX or Node@MinimumSupportedX, since its quite inconsistent 

We want to run our CI pipeline on Windows and Linux for both the "Maintenance LTS" and "Current" releases of nodejs. So that is v10 and v14 respectively. The e2e tests take longer to run, so we're happy to only run them on Windows and Linux for one of the node versions.

**Comment by kmdrGroch** [comment]
So in summary:
- e2e tests have independent packages, on which we should add some reminder after 3-6months
- @types/sinon fix will be done by you
- Change ^ to ~, leave linting at "" and change own deps to ""(?) [I dont know if linter can handle it tho :/, I could try making my own app for this tho]
- no lock files

what about @types/node? Should we use the LTS version or current version (you can specify only 1 in package.json)

**Comment by kmdrGroch** [comment]
> I agree we should use ~ for everything except our own dependencies (@stryker-mutator/api, @stryker-mutator/util, etc). Can we add a linting rule for this?

I have started developing an app to do it. It is so far in beta, but should be working in a week or so :)

**Comment by kmdrGroch** [comment]
@nicojs first attempts with making CLI for this can be seen here: [PackageManager](https://github.com/kmdrGroch/PackageManager). It is still not finished, but it is closer to being done :)

**Comment by kmdrGroch** [comment]
@nicojs finally done it :D 
running it via
```sh
npx pjm
```
with config in root folder like this (still working on configuration, like Regexp configs etc [help appreciated :x]):
[pmj.conf.json](https://github.com/stryker-mutator/stryker/files/5042675/pmj.txt)
[github doesnt allow JSON files]
it should result with "nice" log file like this:
[packageManager.log](https://github.com/stryker-mutator/stryker/files/5042679/packageManager.log)
