### ISSUE TITLE
Feature Request: Support Ava.js for Stryker

### ISSUE THREAD

**Issue by lirantal** [stryker-mutator/stryker#243]
Ava.js is a test runner, they took a lot from tape so they are very similar from syntax perspective and it has really grown: https://github.com/avajs/ava

I personally use it on my Node.js projects and I'll be more than happy to beta-test any work related to Stryker and Ava.js if someone's able to come up with a solution for it.

Thanks!

**Comment by jeznag** [comment]
It may be tricky because Ava spawns processes for each test file. Stryker does the same thing. Not sure whether a subprocess can spawn another process. Also not sure how to access the results. Tape offers an object stream where you will have the results of the tests streamed so you can tell exactly which test failed. Do you know if Ava has something similar @lirantal ?

**Comment by lirantal** [comment]
From quickly skimming through the code and the repo I don't think Ava has support for that.

**Comment by nicojs** [comment]
> Not sure whether a subprocess can spawn another process.

Yes it can, that's not a problem. I would like the `stryker-ava-runner` to run the tests *in the same process*, that way the stryker coverage analysis works out-of-the-box (it uses global variables which do not span multiple processes).

@lirantal ava would indeed be a good addition. Is there a public api? Or an example of using ava from a node process (not via command line). Do you know someone of the avajs team that could help us with this?

**Comment by novemberborn** [comment]
> Is there a public api? Or an example of using ava from a node process (not via command line).

There is no API that's guaranteed to be stable, no. You can require a Node.js module into the forked process however, perhaps that can be used to change how a source file is loaded so that it can be mutated.

**Comment by nicojs** [comment]
@novemberborn thanks for your reply!

Would Avajs be interested in a public api? For inspiration: this is our generic interface that a stryker-testrunner plugin implements for every test runner: https://github.com/stryker-mutator/stryker-api/blob/master/src/test_runner/TestRunner.ts

**Comment by novemberborn** [comment]
> Would Avajs be interested in a public api?

Eventually, yes. But not yet.

**Comment by lirantal** [comment]
Thanks for dropping by @novemberborn

**Comment by simondel** [comment]
@novemberborn Is there any update on the public api?

**Comment by novemberborn** [comment]
@simondel not really, no.

https://github.com/avajs/ava/issues/1692 may be of interest: it'd be a way to run assertions without necessarily failing a test.

https://github.com/avajs/ava/issues/1769 contains a suggestion for AVA to load code into its process that can then interact with test runs.

If either of those make sense for Stryker let me know!

**Comment by macabeus** [comment]
I also would like support Ava.js for Stryker. In my job we have many projects that uses Ava, and the Stryker will be useful.

**Comment by novemberborn** [comment]
@macabeus if you could help with the issues I [linked to previously](https://github.com/stryker-mutator/stryker/issues/243#issuecomment-392021748) that'd be fantastic.

**Comment by simondel** [comment]
Since we've had this issue open for almost two years now, we're closing this issue. It should be possible to run your project using the command test runner. More info on that can be found here: https://stryker-mutator.io/blog/2018-12-24/anouncing-stryker-0-34

**Note:** We've recently released v1 of Stryker. So the commands to update Stryker in that blog are a bit outdated. If anyone runs into any issues, let us know!
