### ISSUE TITLE
Create a realtime-clear-text reporter

### ISSUE THREAD

**Issue by jeznag** [stryker-mutator/stryker#256]
Would be helpful to know of surviving mutants while the test is still running in case of a test suite that runs really slowly.

Goal would be to start work on killing the surviving mutants while the rest of the mutant tests are running.

Output would be similar to clear-text but reported in real time.

**Comment by nicojs** [comment]
Cool. Could't we change the clear-text reporter instead of creating a new one? Why not add a config option 

```typescript
clearTextReporter: { 
  realtime: true    
}
```
You'll get all options injected in the reporter, so you can check this option with:

```typescript
this.options['clearTextReporter']['realtime']
```

**Comment by jeznag** [comment]
@nicojs is this what you meant by adding the reporter option? https://github.com/stryker-mutator/stryker-api/pull/18

**Comment by simondel** [comment]
Thanks for the work! We've changed the way that Stryker works. We have merged stryker and the api into one repository (this one) and we now couple connect our modules using LernaJS which makes it easier to make changes to the stryker-api and use them in stryker without having to do prereleases all the time.

So unfortunately you will have to re-do a bit of your work because the structure of the project has changed. To make this easier I've invited you to become a collaborator so you can make branches here so we can also easily make changes.

On topic:
I would suggest also logging other mutants that have been tested as debugging statements. What do you think?

If you need help getting started with our new project structure, let us know!

**Comment by simondel** [comment]
The reporter API is public so it's possible to add this as a plugin. We're closing this issue for now. If anyone wants to pick this up and needs help, let us know!
