### ISSUE TITLE
Incorrect results with vue SFC

### ISSUE THREAD

**Issue by Djaler** [stryker-mutator/stryker#2775]
**Summary**

If I run stryker mutations on vue-file, it returns me completely incorrect results.

Looks like something wrong with line counting because of template block

**Stryker config**

```js
module.exports = {
    plugins: [
        '@stryker-mutator/jest-runner',
    ],
    reporters: [
        'html',
        'progress',
        'event-recorder',
    ],
    testRunner: 'jest',
    coverageAnalysis: 'perTest',
    disableTypeChecks: false,
    mutate: [
        'src/components/core/Button.vue',
    ],
};
```

**Stryker environment**

```
+-- @stryker-mutator/core@4.4.1
+-- @stryker-mutator/jest-runner@4.4.1
```

```
+-- jest@26.6.3
```

Here you can see report files generated by version 3 and version 4. In version 3 it works good
[v3.zip](https://github.com/stryker-mutator/stryker/files/6068465/v3.zip)
[v4.zip](https://github.com/stryker-mutator/stryker/files/6068469/v4.zip)

**Comment by nicojs** [comment]
Thanks, @Djaler I've seen this myself once but didn't have the opportunity to investigate this further. It also happens in our e2e tests:

![image](https://user-images.githubusercontent.com/1828233/109954517-b7ea3f00-7ce1-11eb-949e-e1a7f85214e3.png)


For anyone unfamiliar, I think SFC means Single File Component.

**Comment by Djaler** [comment]
I found the source of the issue!
https://github.com/stryker-mutator/stryker/blob/10bf19e70574959bda3b392c2bf181137764b90e/packages/instrumenter/src/util/syntax-helpers.ts#L86
Somehow when `node.loc.end.line` was modified on parent node, it was modified in child nodes too.
For example, when `node.loc.end.line` modified for ImportDeclaration node from 2 to 9, I see that `node.source.loc.end.line` has value 9 too (but start wasn't modified). I still don't understand how does this happen. Some deep babel parser magic? 
But we can just deep clone whole ast before offsetLocations to prevent such weird things. I tried, it works correctly

**Comment by Djaler** [comment]
I think about this again and understood that this is not magic. This is just a bug in babel, they assign same Position object to parent and child nodes

**Comment by Djaler** [comment]
https://github.com/babel/babel/issues/12980

**Comment by Djaler** [comment]
I made a fix in babel (https://github.com/babel/babel/pull/12981). We have two options now - wait for merge and then update babel-parser version or just make some workaround just now

**Comment by nicojs** [comment]
Wow! Great find! I'm not sure if they would really classify it as a bug because offsetting locations like that might not be considered a valid use case. 

We could think of _not offsetting locations_ in the babel, instead, we could add a `lineOffset` in the `BaseAst` here:

https://github.com/stryker-mutator/stryker/blob/3b57ef23dd5b348dcdff205600989aea2c7fbcf0/packages/instrumenter/src/syntax/index.ts#L17-L21

And pass that offset to the `MutantCollector` here: 

https://github.com/stryker-mutator/stryker/blob/4fce38f97554626885224b6152da051c780caa59/packages/instrumenter/src/transformers/babel-transformer.ts#L25-L27

That way we don't have to rely on updating locations in the babel AST.

**Comment by Djaler** [comment]
Yeah, that's work
