### ISSUE TITLE
Stryker is currently not installed loop

### ISSUE THREAD

**Issue by mjh5153** [stryker-mutator/stryker#414]
When I go to run the command Stryker run, I keep getting prompted that Stryker is currently not installed.  I can see that Stryker and Stryker-api are installed via node modules and package.json.
![screen shot 2017-10-10 at 2 03 50 pm](https://user-images.githubusercontent.com/11745338/31402427-f46387de-adc3-11e7-9475-ec72b2de1b3b.png)

**Comment by simondel** [comment]
Thanks for opening this issue! This is a bug in the stryker-cli that we've been meaning to fix. When an error occurs it tells you that stryker is not installed instead of showing the error.

In the mean time, could you check if you have stryker-api installed? One of the first lines tells you that you're missing the peer dependency. Also, you could try to run stryker using `node_modules/.bin/stryker run` or adding `stryker run` to an npm script.

**Comment by nicojs** [comment]
@simondel i know you were working on a fix. Is that still true?

**Comment by simondel** [comment]
@nicojs It is on my backlog but I don't have time to fix it right now (I would have some time sunday). If you want to fix it before I come around to it, feel free to do so 👍

**Comment by mjh5153** [comment]
Cool thanks.  I assumed it was something I was doing wrong. Also the reason why I'm getting an error is because I tried to get stryker working with stryker-typescript as a hail mary to use stryker even though I know typescript is not supported yet.  Is there a release date set for the 1.0.0 version of stryker that includes typescript support?  My team uses es6 and typescript and we want to use stryker as well.

**Comment by nicojs** [comment]
I'm closing this issue here stryker cli is still its separate git repo, so i opened an issue here: https://github.com/stryker-mutator/stryker-cli/issues/28

I also created a [PR for fixing this issue](https://github.com/stryker-mutator/stryker-cli/pulls/27).

@mjh5153 we have official support for typescript since stryker v0.10 (current version is 0.11.2). ES6 support is next on our radar.

See [stryker-typescript's readme](https://github.com/stryker-mutator/stryker/tree/master/packages/stryker-typescript#readme) for more info. Please contact us on [gitter](https://gitter.im/stryker-mutator/stryker) if you need any help setting stuff up.

**Comment by mjh5153** [comment]
Okay so I can download and use stryker ^v0.1?

**Comment by nicojs** [comment]
Yes, but don't do that, try ^0.11 ;)
