### ISSUE TITLE
Add support for mutating Javascript vNext

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#429]
We should add support for mutating JavaScript vNext (6, 7, etc).

This issue tracks the work done on branch [stryker-es6-mutator](https://github.com/stryker-mutator/stryker/tree/stryker-es6-mutator)

Todo:

- [x] Rewrite current es5 mutators using babel
- [x] Remove `IdentitifiedNode`
- [x] Rename to stryker-javascript-mutator
- [ ] Add unit tests for mutators
- [x] Add deprecation warning when using the es5 mutator.

This issue is closely related to #133

**Comment by simondel** [comment]
@nicojs What do you think of this message?
![image](https://user-images.githubusercontent.com/4221997/31821851-c4891908-b5a6-11e7-8259-4a1deb687f01.png)

**Comment by nicojs** [comment]
@j-truax that is correct. Since Stryker is now [language agnostic](http://stryker-mutator.github.io/blog/2017-10-06/typescript-support.html#language-agnostic) we've chosen to move out the code for mutating JavaScript. This new implementation is based on babel, which can be a pretty large dependency, especially if you don't need it (for example, when mutating typescript code). So Stryker itself won't be mutating code anymore (which is a little bit ironic for a mutation testing framework). We will give people some heads-up time with this deprecation warning.

> What do you think of this message?
> ![message](https://user-images.githubusercontent.com/4221997/31821851-c4891908-b5a6-11e7-8259-4a1deb687f01.png)

How about: `DEPRECATED: The es5 mutator is deprecated and will be removed in the future. Please upgrade to the stryker-javascript-mutator (npm install --save-dev stryker-javascript-mutator) and set "mutator: 'javascript'" in your stryker.conf.js!`

**Comment by j-truax** [comment]
@nicojs Thanks for the clarification. Glad we are not losing ES5 support :+1: 

And yes that is ironic :smile: for a mutation framework.

Either message seems sufficient to me

**Comment by simondel** [comment]
I've changed the message to your suggestion @nicojs 👍

**Comment by FezVrasta** [comment]
Is this going to support any babel plugin? (JSX, stage-2 etc?)

**Comment by simondel** [comment]
@FezVrasta Not in the initial version but we plan on adding it later on. If you look at [this line](https://github.com/stryker-mutator/stryker/blob/stryker-es6-mutator/packages/stryker-javascript-mutator/src/helpers/BabelParser.ts#L6) we don't specify any options object. In the future we could pass an [options object with a plugins sections](https://babeljs.io/docs/usage/api/#options). This however won't fix everything as the stryker plugin may not know how to mutate the code.

Note that this plugin is merely for mutating the code. If the input was ES2017 code, the output will be ES2017. In order to run ES2017 code in your environment you may have to transpile it to ES5. That will be handled by a plugin like _stryker-babel-transpiler_ which we plan on developing in the future.

Is your code open source? If not, a demo project would help us test the plugins early on 👍

**Comment by FezVrasta** [comment]
Not open source sorry, anyway it's just a create-react-app 👍
