### ISSUE TITLE
Ignoring invalid mutations that can't flag test failures

### ISSUE THREAD

**Issue by mscharley** [stryker-mutator/stryker#457]
```
export const validatePageCount = (count: number | undefined): number => {
  if (count === undefined || count > maxNumOfArticles || count < 1) {
    return maxNumOfArticles;
  }

  return count;
};
```

This is flagging up in stryker because the `count > maxNumOfArticles` could be `>=` or `>` which will change the control flow inside the function but not the result and hence the change is untestably different. is there some way to flag certain instances of a mutation as not mattering? or some other way to fix this?

**Comment by nicojs** [comment]
This is what's called an equivalent mutant. The mutant results in the same effect as the original code. It's a challenge for any mutation testing framework. 

We've decided to not worry about equivalent mutants for now because they are impossible to detect automatically. This is why you shouldn't target 100% mutation score, better to target 95% or something.

We are thinking of ways disable mutators, but that would first only allow you to disable an entire class of mutations (for example: disabling the `Block` mutator).

What would your suggestion be for this issue?

**Comment by mscharley** [comment]
So, realistically, in the project it's happening it's merely a distraction - our overall coverage is at around 40% at the moment so we've got bigger fish to fry. It's just annoying that we can't ignore it so that we know were to actually focus our attention.

I'm not sure I have any specific suggestions, as you say, it's a tough issue. You're talking about some sort of flag that can target a very specific piece of code (perhaps down to the character level). Any flag outside the code being tested is liable to get out of date, and anything inside the code would be distracting. Perhaps a comment like `tslint` such as:

```
// stryker:disable-next-line:BinaryExpression
if (count === undefined || count > maxNumOfArticles || count < 1) {
```

**Comment by simondel** [comment]
We have no plans to support this use case right now, so I'm closing this issue.
