### ISSUE TITLE
Stryker does not work with babel plugins

### ISSUE THREAD

**Issue by guigonc** [stryker-mutator/stryker#553]
Stryker presents an error while creating mutants and encounters sintax transpiled with babel plugins.

The repo https://github.com/guigonc/stryker-test-config has an example of `transform-object-rest-spread` but the error also happened with `transform-class-properties`

**Comment by nicojs** [comment]
@Archcry would it be possible to include all plugins that the user installed? Is there a way to distinguish them from other npm dependencies?

**Comment by Archcry** [comment]
Well the user does not install any of the plugins, they are all available through babylon. It's just that the user does not define babylon plugins in their project because they don't use babylon. They only use babel. In Stryker babylon is used to generate the abstract syntax tree and therefore it has nothing to do with the user's project setup. The babel plugins also don't match the babylon plugins.

So there are two options:
- Make the user define things he doesn't know about and probably does not want to care about.
- Include some sensible default that will not work in exotic situations.

**Comment by simondel** [comment]
Well, it is something we may want to fix. However, `babel.parse` will be in Babylon 7 which is not out yet (without beta)

**Comment by simondel** [comment]
We haven't heard from people actually having issues with this for a while, so I'll close it for now.
