### ISSUE TITLE
Drop Node 4 support

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#674]
On 30-04-2018 we will drop support for Node 4. The minimal supported Node version for Stryker will be version 6.

If you are still using Node 4, please contact us!

**Comment by nicojs** [comment]
Best birthday present ever

**Comment by simondel** [comment]
We should be able to upgrade Inquierer to v5.x if we drop Node 4 support. There may be other dependencies.

**Comment by nicojs** [comment]
Well the number 1 reason for dropping the support is that node 4 will no longer be supported by the nodejs release working group: https://github.com/nodejs/Release#release-schedule

Other improvements for us is that we can tryout targeting es6 with typescript. That would clean up our JS code a whole lot. Not sure about that one yet, we might need to wait another year for that.

We also use the `Buffer.from` syntax in some tests (disabled for node4) and for example angular is not supporting node 4, so our integration tests with angular don't run on node4, etc. Its a general hassle to maintain it. 

@j-truax Good to know that we didn't do it for nothing (since you still need to work with node 4). Out of curiosity, why? :)

**Comment by j-truax** [comment]
@nicojs Thanks for the extra info :+1: I didn't mean to imply you were doing it for nothing. I was just genuinely curious to get a preview of how this upgrade enable better/new features in Stryker. Particularly around execution time since we have experience slowdowns with larger JS projects.

Are you asking why I am still on Node 4? 
- If so, newer versions of Node were made available in the recent past where I work. The particular application I am working on is a side initiative that I have to work on in my free time. As such, when I get time I have typically used it to build out additional features. I do have a task for upgrading Node on my backlog. I imagine client facing applications will migrate over time as they receive funding for enhancements from the business.

**Comment by simondel** [comment]
@j-truax Thanks for making us aware that you're still running on node 4! 

The changelog of every package will contain a record of when we drop node 4 support, allowing you to see what the last supported version is. We could also post the last supported version in this issue when we migrate :)

**Comment by nicojs** [comment]
Work done in PR #724

**Comment by simondel** [comment]
This has been released with:
https://github.com/stryker-mutator/stryker/commit/9a47808a0fa68115779c832fca667e3a926d0222
