### ISSUE TITLE
EMFILE on linux with simple mocha setup

### ISSUE THREAD

**Issue by adrianheine** [stryker-mutator/stryker#696]
### Summary

In my pretty simple and small mocha-based setup, ryker fails to start with `EMFILE: too many open files`. gracefulifying in `stryker/src/StrykerCli.js` works around this:

```js
var realFs = require('fs')
var gracefulFs = require('graceful-fs')
gracefulFs.gracefulify(realFs)
```

### Stryker config

```js
module.exports = function(config) {
  config.set({
    testRunner: "mocha",
    mutator: "javascript",
    transpilers: [],
    reporter: ["clear-text", "progress"],
    testFramework: "mocha",
    coverageAnalysis: "perTest",
    mutate: ["*.js"],
  });
};
```

### Stryker environment

```
├─┬ stryker@0.22.1
├─┬ stryker-api@0.16.0
├─┬ stryker-javascript-mutator@0.6.2
├─┬ stryker-mocha-framework@0.9.1
└─┬ stryker-mocha-runner@0.11.1
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             | 8.9.3
| npm              | 5.6.0
| Operating System | Linux 4.15.0-2-amd64 #1 SMP Debian 4.15.11-1 (2018-03-20) x86_64 GNU/Linux

**Comment by nicojs** [comment]
Right now our file globbing logic is something stryker does in https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/src/input/InputFileResolver.ts This is not the best code ever, we should improve that part. It does not take the amount of file handles into account.

A possible solution would be to use something like [fast-glob](https://www.npmjs.com/package/fast-glob). The problem is that it uses many dependencies. We would also lose the functionality that it logs a warning if a glob expression resulted in no files, we might want to keep that warning as it can help end users.

**Comment by Mrna1** [comment]
Hi, I'm having the same issue on my project.
10:39:04 (14184) ERROR StrykerCli an error occurred { [Error: EMFILE: too many open files, open .....
errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: ....

Do you have any documented solution?

**Comment by simondel** [comment]
We've recently changed the way we load files. If this issue is still present with Stryker v1 (`@stryker-mutator/core` and friends), let us know and we'll reinvestigate!
