### ISSUE TITLE
Exclude files from glob expression

### ISSUE THREAD

**Issue by jordyheutinck** [stryker-mutator/stryker#95]
Node glob has an option which enables files to be excluded from a glob expression.

```
var glob = require('glob');

glob("**/*",{"ignore":['index.html', 'js', 'js/app.js', 'js/lib.js']}, function (err, files) {
  console.log(files);
})
```

[Node glob documentation](https://github.com/isaacs/node-glob#options)
Adding this feature to the Stryker config file would make configuring Stryker for larger projects a lot easier and less time consuming.

**Comment by simondel** [comment]
Thanks for your input!

How would you prefer to exlude files? Would you like to use special characters such as `!` to prefix globbing patterns or would you prefer to have separate arrays in the config such as `ignoreFiles` and `ignoreMutate`? Or do you have a different solution?

**Comment by jordyheutinck** [comment]
You're welcome!
I'm not sure what the most viable solution would be, but I like the idea of specifying ignored files through an array inside the files or mutate array.

For example,
 ```
config.set({
        files: [
            'src/lib/jquery/dist/jquery.js',
            'src/lib/angular/angular.js',
            'src/resources/js/**/*.js',
            ignore: [
                '**/*Mock.js'
            ]
        ],
        mutate: [
            'src/resources/js/**/*.js',
            ignore: [
                '**/SomeOtherGlobPattern.*'
            ]
        ]
});
```

For consistencies sake you could also choose to use Karma's solution, which is the separate array you mentioned.

**Comment by nicojs** [comment]
I would also choose to have consistency. Like `exclude` and
`excludeMutate`. The excluded files would also count as excludeMutate files

You're welcome!
I'm not sure what the most viable solution would be, but I like the idea of
specifying ignored files through an array inside the files or mutate array.

For example,

config.set({
        files: [
            'src/lib/jquery/dist/jquery.js',
            'src/lib/angular/angular.js',
            'src/resources/js/**/*.js',
            ignore: [
                '**/*Mock.js'
            ]
        ],
        mutate: [
            'src/resources/js/**/*.js',
            ignore: [
                '**/SomeOtherGlobPattern.*'
            ]
        ]
});

For consistencies sake you could also choose to use Karma's solution, which
is the separate array you mentioned.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/stryker-mutator/stryker/issues/95#issuecomment-215378098>

**Comment by nicojs** [comment]
@jordyheutinck Could you please test the new release of Stryker? You should be able to exclude files using `!` as explained in the readme

**Comment by simondel** [comment]
I'll close this issue for now. Could you let us know if it's not fixed?
